### ISSUE TITLE
Could you upload dataset files in the first step?

### ISSUE THREAD

**Issue by Anderbone** [STayinloves/NMT2017-ZH-EN#2]
Since we need to download 'all dataset required in the WMT 2017 MT task'
However, the ftp server inside this [cwmt-wmt](http://nlp.nju.edu.cn/cwmt-wmt/) is broken.
 Anyone has these files and are willing to share? 
Thanks a lot.

**Comment by sanxing-chen** [comment]
You should contact NLP@NJU in the first place to check the service status with them.

I’m not sure if I have the right the redistribute the data, sorry.
